export const drivers = [
  { driver: "Max Verstappen", team: "Red Bull Racing" },
  { driver: "Sergio Perez", team: "Red Bull Racing" },
  { driver: "Lewis Hamilton", team: "Ferrari" },
  { driver: "Charles Leclerc", team: "Ferrari" },
  { driver: "Lando Norris", team: "McLaren" },
  { driver: "Oscar Piastri", team: "McLaren" },
  { driver: "George Russell", team: "Mercedes" },
  { driver: "Kimi Antonelli", team: "Mercedes" },
  { driver: "Fernando Alonso", team: "Aston Martin" },
  { driver: "Lance Stroll", team: "Aston Martin" },
  { driver: "Pierre Gasly", team: "Alpine" },
  { driver: "Jack Doohan", team: "Alpine" },
  { driver: "Carlos Sainz", team: "Williams" },
  { driver: "Alexander Albon", team: "Williams" },
  { driver: "Nico Hulkenberg", team: "Sauber" },
  { driver: "Gabriel Bortoleto", team: "Sauber" },
  { driver: "Yuki Tsunoda", team: "RB" },
  { driver: "Liam Lawson", team: "RB" },
  { driver: "Kevin Magnussen", team: "Haas F1 Team" },
  { driver: "Oliver Bearman", team: "Haas F1 Team" },
];
